Project 1: create animals table.
joramot/vetclinicdb pull request #1
Opened 2023-10-31 22:14 UTC by joramot

**### Project requirements**

- Used the template to generate the repo.
- Created a database named vet_clinic.
- Created a table named animals whit the columns.
- Inserted the data in the animals table.
- Wrote and executed queries for each quest.
- Took a screenshot of the results of your queries.

![1 Find all animals whose name ends in mon ](https://github.com/joramot/vetclinicdb/assets/1154879/e3d0db0d-5533-4015-9c6f-ac73b59c80d8)
![2 List the name of all animals born between 2016 and 2019](https://github.com/joramot/vetclinicdb/assets/1154879/8aa7e84f-a83e-4be3-9e6d-09b1501bfbe8)
![3 List the name of all animals that are neutered and have less than 3 escape attempts](https://github.com/joramot/vetclinicdb/assets/1154879/804f53a7-96f7-4aa1-83ce-a35f56f92a84)
![4 List the date of birth of all animals named either Agumon or Pikachu](https://github.com/joramot/vetclinicdb/assets/1154879/3be82c22-9ee4-488f-a3dd-b94fdbcf5259)
![5 List name and escape attempts of animals that weigh more than 10 5kg](https://github.com/joramot/vetclinicdb/assets/1154879/1c37581c-3213-4c44-bd33-ea27ed73e513)
![6 Find all animals that are neutered](https://github.com/joramot/vetclinicdb/assets/1154879/75ddf673-95db-428c-a451-ee21aab21df7)
![7 Find all animals not named Gabumon](https://github.com/joramot/vetclinicdb/assets/1154879/60b08afa-180c-4474-85ae-760904802314)
![8 Find all animals with a weight between 10 4kg and 17 3kg (including the animals with the weights that equals precisely 10 4kg or 17 3kg)](https://github.com/joramot/vetclinicdb/assets/1154879/2f90d3ba-671d-49ca-b05a-f7c44ffa6248)

2023-10-31 23:04 UTC, skyv26 requested changes
## Hi @joramot, 

Good job so far 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNjVhZjBiZjUzZmYxZjI1NGFhNGQ0ZjIyN2FhOTcwNDZlZmUzNmZkMiZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/L422JoNlBBBD42zkQ9/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 

## Required Changes ♻️
- [ ] Dear @joramot, you did a super cool job by implementing the things as per the requirement, I saw that your results are accurately matching and everything is perfect except one thing, which is the only cause that you have to re-submit your project for the review. I noticed that you have used the `Microverse` **README** template but forgot to alter the documentation with relevant information, as instructed at the very beginning of the journey into *Microverse*. Kindly remove the unnecessary section from your `README` file, and add everything relevant and related to this project.

- [ ] It would be nice if instead of adding the images in your repository, you could either put all the images inside the folder **OR** you can remove them because your screenshots can be uploaded through the github `attach` files feature.
 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-01 03:55 UTC, TadesseDev requested changes
### Hi @joramot 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![199733072-bdacca19-8df9-43a7-be93-3aff2f1c15c8](https://user-images.githubusercontent.com/69077061/204107907-c2532abb-b23d-4fda-88f0-1ec9c7b71971.gif)

 ## Highlights
 - [x] Good job making most of the changes requested by the previous reviewer. 🙏


 ## Required Changes ♻️
#### While you did a great job updating your readme as suggested earlier, Please notice the following facts.
- [ ] Please notice the section in your readme which starts with `>` are directions/guidelines from microverse to help you understand what to write in that section and should not be part of your readme file. Please consider removing this and all the like contents from the readme file. Please remove the `> Give credit to everyone who inspired your codebase.` part in your Acknowledgement section. 
- [ ] Also, Your licence section has section description text which shouldn't be part of your readme file.

 _Check the comments under the review._

## Optional suggestions

- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-01 03:55 UTC, TadesseDev commented on README.md
> +> coming soon...
- [ ] Good job updating the readme file as suggested by the previous reviewer, but please consider removing the `Live demo` section from the readme file. It is only required when you have a project that is deployed. This is a mandatory requirement for all projects.

2023-11-01 04:38 UTC, mukhammadrizooff approved these changes
Hi @joramot, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

<img src="https://media4.giphy.com/media/sR9nilEznDoSlga667/giphy.gif"/> 

## Highlights
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-02 14:22 UTC, merged